### ISSUE TITLE
Get webform form ?

### ISSUE THREAD

**Issue by Thommusa** [duartegarin/graphql_webform#1]
Is it possible/plan to get the webform form by graphql ? except I'm wrong and it's already done, but I think for now we can only get submission?

**Comment by duartegarin** [comment]
Hi @Thommusa ,
This is just a WIP and I haven't touched it in ages, but it does get the webform, not the submission.

**Comment by askibinski** [comment]
I took this module out for a spin and it works. Here is some explanation and a basic example.

- The module depends on the graphql_json module which provides fields to consume json data
- graphql_webform provides some fields to get the webform and elements and provides all the elements as JsonObjects which can then be queried.

Example query which gets the type and title values for all elements of a webform:

`{
  webformById(webform_id: "my_webform_id_string") {
    ... on WebformResult {
      webform {
	      elements {
          ... on JsonObject {
            type: path(steps: ["#type"]) {
              ... on JsonLeaf {
                value
              }
            }
            title: path(steps: ["#title"]) {
              ... on JsonLeaf {
                value
              }
            }
          }
        }
      }
    }
  }
}`

While this works I have some questions/remarks:

1. Everything is made available through a JsonObjects, but we are not actually dealing with JSON data are we? It's just Drupal's PHP arrays.
2. While you can retrieve a lot this way, you would have to rebuild a lot of logic in your decoupled frontend so another approach might be to provide data which more easility integrates react components like https://www.gatsbyjs.org/packages/gatsby-drupal-webform.

**Comment by carolpettirossi** [comment]
@askibinski, thanks for your feedback. Just want to let you know that I've just pushed to the dev branch a new version of this module which is currently under development but it does work with simple/small webforms. 

You can have a look at the dev branch: https://github.com/duartegarin/graphql_webform/tree/dev. There's also initial documentation on how to retrieve the webform elements and how to create a submission.

**Comment by askibinski** [comment]
@carolpettirossi Nice! I'm currently implementing this, will create issues/PR if I stumble upon issues.

I guess this issue can be closed.
