### ISSUE TITLE
Move development back to drupal.org

### ISSUE THREAD

**Issue by pfrenssen** [duartegarin/graphql_webform#26]
This module started its development on Github back in 2018. In the meantime drupal.org has adopted a more modern development workflow using Gitlab merge requests.

Would it be possible to move the development back to drupal.org? Then we can benefit from its features that are missing from Github, such as collaborative merge requests, integration with the drupal.org issue queues and running automated tests.

**Comment by duartegarin** [comment]
Hi @pfrenssen ,
Thanks for reaching out!
The reality is I'm just not actively maintaining this anymore with the exception of a project that uses it (and probably not for that much longer).
I just saw your other issue around proposing to co-maintain this which I think would be great.
Let's proceed with that!
