### ISSUE TITLE
Request for co-maintainership

### ISSUE THREAD

**Issue by pfrenssen** [duartegarin/graphql_webform#28]
I would like to help out maintaining this module. My employer (https://www.liip.ch/) is using it for a number of our client projects and we would like to keep using it moving forward.

My goals are:
* Implement basic test coverage.
* Support GraphQL 4.
* Support Drupal 10.
* Support PHP 8.1.
* Move development back to drupal.org

**Comment by duartegarin** [comment]
Hi @pfrenssen ,
Thanks for volunteering!
I think it's great, given I just don't have the time to take this on at the moment.
I agree with all your points, just need to ensure you keep a 3x compatible version for GraphQL. Given the complete difference in 3x and 4x they need to be separate releases unfortunately and still quite a few people use 3x.
Let me know if you need anything else!

**Comment by duartegarin** [comment]
Ah one, other thing.
As soon as you have things up and running in Drupal.org let me know and I can archive this in Github to avoid confusion (and redirect people back to d.o)
Thanks!

**Comment by pfrenssen** [comment]
Thanks! I will open a 2.x branch to support the new versions of GraphQL, Drupal and PHP. The current 8.x-1.x branch will remain on GraphQL 3 for Drupal 8 + 9.
