### ISSUE TITLE
Remove deprecated WebformElements

### ISSUE THREAD

**Issue by askibinski** [duartegarin/graphql_webform#4]
When testing the new dev version, I didn't get any of the webformelements. Turns out the old WebformElements was also still available and used.

PR: #3

**Comment by carolpettirossi** [comment]
copy pasting my comment from the PR here:

Hi askibinski,

Thanks for reporting this issue. The code was actually outdated and I'm sorry about that. I've just pushed a new version to the dev branch.
The WebformElements is actually necessary to:

Add the plugin and allow future checks in each WebformElement type.
For example, WebformElementCheckboxes has this check

  public function applies($object, ResolveContext $context, ResolveInfo $info) {
    return $object['plugin'] instanceof Checkboxes;
  }
Add elements of the Webform and WebformComposite to allow this kind of query for example.
{
  webformById(webform_id: "contact") {
    __typename
    description
    elements {
      __typename
      id
      type
      ... on WebformElementTextarea {
        title
      }
      ... on WebformElementComposite {
        elements {
          id
          type
          ... on WebformElementTextField {
            title
          }
        }
      }
    }
  }
}
Would you mind testing the latest version pushed to dev branch?

Thanks,
Carol

**Comment by duartegarin** [comment]
@carolpettirossi  given it's been almost a month, should we close this issue? (and the PR).

**Comment by carolpettirossi** [comment]
I agree with you, @duartegarin. Closing it.
