### ISSUE TITLE
WebForm Options not being returned when WebForm Options used

### ISSUE THREAD

**Issue by wyckojr** [duartegarin/graphql_webform#6]
We are unable to get the options returned via GraphQL for a "Select" field type. We are using a predefined list of options, as defined inside of the Webform module:

![image](https://user-images.githubusercontent.com/19615213/80540747-82612080-896f-11ea-9eac-afc45d0da776.png)

Going to the options lists takes us here:
![image](https://user-images.githubusercontent.com/19615213/80540811-a290df80-896f-11ea-8cfb-0f10a9478b9a.png)

And editing a list looks like this:
![image](https://user-images.githubusercontent.com/19615213/80540979-f26fa680-896f-11ea-8c58-8df3cb9bec81.png)

But in the GQL return, the options are not listed:
![image](https://user-images.githubusercontent.com/19615213/80540913-d3711480-896f-11ea-890e-db577edd5777.png)

Before installing this graphql_webform module, we were able to see the options listed in GraphQL using a more crude query, which no longer works once we've installed the module, but obviously this wasn't useful for using webforms in a headless environment. Nevertheless, it was exposed.:
![image](https://user-images.githubusercontent.com/19615213/80541130-3ebae680-8970-11ea-876e-25923446ca6b.png)

I believe the issue here might be the different types of plugins you are looking for in your code when presented with #options, but we are unsure of how to help with the solution.

**Comment by carolpettirossi** [comment]
Hi @wyckojr, 

Sorry for the late reply. The bug you reported has been fixed and added to the alpha6 release.
